// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbJzNwK_gNXN9wg81jS7ez8yr5SZe6auY',
    appId: '1:287699100626:web:d9b585572214ebf8325e0b',
    messagingSenderId: '287699100626',
    projectId: 'matchmaking-35a64',
    authDomain: 'matchmaking-35a64.firebaseapp.com',
    storageBucket: 'matchmaking-35a64.firebasestorage.app',
    measurementId: 'G-KPY36Y06WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXE3mBggLFALfI28Jqx12kBIRo2345Ldg',
    appId: '1:287699100626:android:99d3264bbcebf331325e0b',
    messagingSenderId: '287699100626',
    projectId: 'matchmaking-35a64',
    storageBucket: 'matchmaking-35a64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTPm6b5SRVVK7Fe3yJ3uV73h-3ltD1MPw',
    appId: '1:287699100626:ios:20d77571dd5cc90f325e0b',
    messagingSenderId: '287699100626',
    projectId: 'matchmaking-35a64',
    storageBucket: 'matchmaking-35a64.firebasestorage.app',
    androidClientId: '287699100626-a8r58gvbgrkcgqb8o6uj7lb41pdmqik1.apps.googleusercontent.com',
    iosClientId: '287699100626-gj4cnprujtpj10e4n1ao8qvqbmvngqpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediatorMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTPm6b5SRVVK7Fe3yJ3uV73h-3ltD1MPw',
    appId: '1:287699100626:ios:20d77571dd5cc90f325e0b',
    messagingSenderId: '287699100626',
    projectId: 'matchmaking-35a64',
    storageBucket: 'matchmaking-35a64.firebasestorage.app',
    androidClientId: '287699100626-a8r58gvbgrkcgqb8o6uj7lb41pdmqik1.apps.googleusercontent.com',
    iosClientId: '287699100626-gj4cnprujtpj10e4n1ao8qvqbmvngqpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediatorMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbJzNwK_gNXN9wg81jS7ez8yr5SZe6auY',
    appId: '1:287699100626:web:f51c190bd9d42791325e0b',
    messagingSenderId: '287699100626',
    projectId: 'matchmaking-35a64',
    authDomain: 'matchmaking-35a64.firebaseapp.com',
    storageBucket: 'matchmaking-35a64.firebasestorage.app',
    measurementId: 'G-H31ZKF0WNB',
  );
}
